apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ttm-as-a-service-webhook-receiver
spec:
  replicas: 1
  test: false
  selector:
    deploymentconfig: ttm-as-a-service-webhook-receiver
    app.kubernetes.io/name: ttm-as-a-service
    app.kubernetes.io/component: webhook-receiver
    app.kubernetes.io/managed-by: aicoe-thoth-devops
  template:
    metadata:
      labels:
        deploymentconfig: ttm-as-a-service-webhook-receiver
        app.kubernetes.io/name: ttm-as-a-service
        app.kubernetes.io/component: webhook-receiver
        app.kubernetes.io/managed-by: aicoe-thoth-devops
    spec:
      containers:
        - name: ttm-as-a-service-webhook-receiver
          image: quay.io/thoth-station/ttm-as-a-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: GITHUBAPP_ID
              valueFrom:
                secretKeyRef:
                  key: GITHUBAPP_ID
                  name: githubapp-id
            - name: GITHUBAPP_SECRET
              valueFrom:
                secretKeyRef:
                  key: GITHUBAPP_SECRET
                  name: githubapp-secret
            - name: GITHUBAPP_KEY
              valueFrom:
                secretKeyRef:
                  key: GITHUBAPP_KEY
                  name: githubapp-key
      restartPolicy: Always
